"""Poll Elasticsearch for Kibana alerting events and forward them to Edwin."""

from elastic_poller import bookmark, config, dedupe, delivery, elasticsearch, poller
from elastic_poller.bookmark import getBookmark, setBookmark
from elastic_poller.config import (
    OK,
    BOOKMARK_PATH,
    DEBUG,
    EDWIN_ID,
    EDWIN_ORG,
    EDWIN_TOKEN,
    DEXDA_ID,
    DEXDA_ORG,
    DEXDA_TOKEN,
    ELASTIC_BATCH_SIZE,
    ELASTIC_INDEX,
    ELASTIC_PASS,
    ELASTIC_PIT_KEEP_ALIVE,
    ELASTIC_OVERLAP_MS,
    DEDUPE_MAX_RECORDS,
    DEDUPE_MAX_SIZE_MB,
    ELASTIC_QUERY,
    ELASTIC_TOKEN,
    ELASTIC_URL,
    ELASTIC_USER,
    ELASTIC_VERIFY_SSL,
    ERROR_CODE_EVENT_DELIVERY_FAILED,
    ERROR_CODE_EVENT_MAPPING_FAILED,
    ERROR_CODE_HTTP,
    ERROR_CODE_UNEXPECTED,
    ERROR_CODE_UNKNOWN,
    ERROR_CODE_VALIDATION_FAILED,
    LM_LOGS_ACCOUNT,
    LM_LOGS_BEARER_TOKEN,
    LM_LOGS_ENABLED,
    LM_LOGS_RESOURCE_ID,
    LOG_ENABLED,
    FAILED_PAYLOAD_PATH,
    PAUSE_INTERVAL,
    edwin_client_id,
    edwin_client_token,
    edwin_org,
    env_bool,
    getenv_alias,
    has_edwin_credentials,
    logger,
    missing_edwin_credential_names,
)
from elastic_poller.delivery import createEvent, send_event
from elastic_poller.elasticsearch import (
    ElasticsearchQueryError,
    _es_conn_kwargs,
    _es_request,
    build_logs_query,
    close_point_in_time,
    epoch_ms_to_zulu,
    fetch_elasticsearch_hits,
    hit_timestamp_ms,
    open_point_in_time,
    query_elasticsearch,
)
from elastic_poller.poller import poll_cycle, process_hits, readElasticRecords

# Submodule aliases for tests and scripts.
requests = elasticsearch.requests

__all__ = [
    "OK",
    "BOOKMARK_PATH",
    "DEBUG",
    "EDWIN_ID",
    "EDWIN_ORG",
    "EDWIN_TOKEN",
    "DEXDA_ID",
    "DEXDA_ORG",
    "DEXDA_TOKEN",
    "ELASTIC_BATCH_SIZE",
    "ELASTIC_INDEX",
    "ELASTIC_PASS",
    "ELASTIC_PIT_KEEP_ALIVE",
    "ELASTIC_OVERLAP_MS",
    "DEDUPE_MAX_RECORDS",
    "DEDUPE_MAX_SIZE_MB",
    "ELASTIC_QUERY",
    "ELASTIC_TOKEN",
    "ELASTIC_URL",
    "ELASTIC_USER",
    "ELASTIC_VERIFY_SSL",
    "ElasticsearchQueryError",
    "_es_conn_kwargs",
    "_es_request",
    "build_logs_query",
    "bookmark",
    "bookmark_dir",
    "bookmark_file",
    "close_point_in_time",
    "config",
    "createEvent",
    "delivery",
    "dedupe",
    "elasticsearch",
    "epoch_ms_to_zulu",
    "fetch_elasticsearch_hits",
    "FAILED_PAYLOAD_PATH",
    "getBookmark",
    "hit_timestamp_ms",
    "open_point_in_time",
    "poll_cycle",
    "poller",
    "process_hits",
    "query_elasticsearch",
    "readElasticRecords",
    "send_event",
    "setBookmark",
]

bookmark_dir = bookmark.bookmark_dir
bookmark_file = bookmark.bookmark_file
